app:
  name: '@project.name@'
  desc: '@project.description@'
  version: '@project.version@'
  url: http://localhost:8080
  dev-name: None
  dev-email: none@none.com

server:
  port: 8080

springdoc:
  packages-to-scan: ar.edu.utn.frc.tup.lciii.controllers
  show-actuator: true
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true